In [39]:
#EX 1
import numpy as np

X = [[1, 2, 3],  # A has 2 rows and 3 columns
     [4, 5, 6]]

Y = [[7,8,9],
     [10,11,12]]

def matrix_add(A, B):
    return np.matrix(A) + np.matrix(B)
matrix_add(X,Y)

matrix([[ 8, 10, 12],
        [14, 16, 18]])

In [34]:
#EX 2
import numpy as np

# X = [[1, 2, 3],  # A has 2 rows and 3 columns
#      [4, 5, 6]]
#
# Y = [[7,8,9]]
# SAI QUA NGU

def matrix_multiplication(A, B):
    # return np.array(A) * np.array(B) this isn't matrix multiplitcation
    return np.matrix(A).dot(np.matrix(B))
# matrix_multiplication(X, Y) SAI QUA NGU

X = [[1,2,3],[4,5,6]]
Y = [[7,8],
     [9,10],
     [11,12]]
matrix_multiplication(X, Y)

matrix([[ 58,  64],
        [139, 154]])

In [44]:
import numpy as np

def matrix_transpose(A):
    return np.matrix(A).transpose()
X = [[1,2,3],[4,5,6]]
matrix_transpose(X)

matrix([[1, 4],
        [2, 5],
        [3, 6]])